server:
  port: 9001
spring:
  application:
    name: test-provider-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: nacos-test-consumer-dev
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *