spring:
  application:
    name: sentinel-test
  cloud:
    sentinel:
      transport:
        port: 8719     # sentinel console transport port , default 8719 , conflict +1 until success
        dashboard: localhost:8080    # sentinel console view plat
  #  sentinel datasource
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-test
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    nacos:
      discovery:
        server-addr: localhost:8848   # nacos register center
        namespace: nacos-test-consumer-dev

server:
  port: 9004